package com.yaml.app.my_app_yaml;
public enum TokenType {
	//BAR  -
	//QUOTATION_MARK "
	//CONLON :
    IDENTIFIER, ARRAY, STRING, BOOL, INT, DOUBLE, COMMENT, SCIENTIFIC, QUOTATION_MARK, BAR, COLON, EOF, NEWLINE,NULL,KEY_VALUE_inArray
}